"use client";
import { useEffect, useMemo, useRef, useState } from "react";
type Block={id:string;title:string;body:string}; type Entry={id:number;blockId:string;kind:string;status:string;category:string;body:string;createdAt:string};
const blocks:Block[]=[
{id:"cavity-pair",title:"Paired cavity state",body:"Two boron-defined cavities form a differential logical cell. One controlled carrier is shared across the pair, while amplitude and phase encode the relationship between the cavities."},
{id:"opposed-pulses",title:"Opposing pulse cycle",body:"Cavity A and cavity B receive phase-locked drives separated by 180 degrees. The field between them is the active region, and the pulse must preserve the stored relationship rather than force an ordinary alternating switch."},
{id:"color-router",title:"Color-addressed routing",body:"Red routes, blue imports, yellow extracts, green connects, purple assimilates, and orange selects. Each wavelength addresses the same stored information through a different physical transition."},
{id:"measurement-rule",title:"Measurement boundary",body:"The device remains an experimental quantum proposal until coherent phase, oscillation, and interference are measured. Synchronized classical switching is retained as the first useful hardware milestone."}];
export default function Home(){
const[selected,setSelected]=useState<string|null>(null),[entries,setEntries]=useState<Entry[]>([]),[draft,setDraft]=useState(""),[saving,setSaving]=useState(false);const inputRef=useRef<HTMLTextAreaElement>(null);const selectedBlock=useMemo(()=>blocks.find(b=>b.id===selected),[selected]);
useEffect(()=>{fetch("/api/context-entries").then(r=>r.json()).then(d=>setEntries(d.entries??[])).catch(()=>{})},[]);
useEffect(()=>{if(selected)requestAnimationFrame(()=>inputRef.current?.focus())},[selected]);
async function send(){if(!selectedBlock||!draft.trim())return;setSaving(true);try{const r=await fetch("/api/context-entries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({blockId:selectedBlock.id,body:draft})});const d=await r.json();if(!r.ok)throw new Error(d.error??"Unable to record");setEntries(c=>[...c,d.entry]);setDraft("")}finally{setSaving(false);requestAnimationFrame(()=>inputRef.current?.focus())}}
function composer(block:Block){if(selected!==block.id)return null;const thread=entries.filter(e=>e.blockId===block.id);const older=thread.slice(0,-1);const latest=thread.at(-1);return <div className="inlineThread"><div className="contextChip"><span>↳</span><div><small>Replying beneath</small><strong>{block.title}</strong></div><button onClick={()=>setSelected(null)} aria-label="Return composer to bottom">×</button></div>{older.length>0&&<details className="olderTurns"><summary>Earlier branch conversation ({older.length})</summary>{older.map(e=><div className="branchTurn" key={e.id}><div className="humanTurn"><span>You</span><p>{e.body}</p></div><div className="aiTurn"><span className="aiMark">✦</span><p>Filed with this paragraph’s context.</p></div></div>)}</details>}{latest&&<div className="branchTurn latest"><div className="humanTurn"><span>You</span><p>{latest.body}</p></div><div className="aiTurn"><span className="aiMark">✦</span><div><strong>Newest context remains open</strong><p>Earlier information is preserved behind the arrow while this addition stays readable in the main flow.</p></div></div></div>}<div className="composer"><textarea ref={inputRef} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="Continue this part…" rows={1}/><button onClick={send} disabled={saving||!draft.trim()} aria-label="Send">{saving?"…":"↑"}</button></div><p className="quietNote">Context, category, status, and history are filed automatically.</p></div>}
return <main><header><button aria-label="Menu">☰</button><div><strong>Oxide computer research</strong><small>Structured conversation</small></div><button aria-label="More">•••</button></header><section className="conversation"><div className="userBubble">I want the oxide computer explained as paired cavities, magnetic pulses, and color-addressed routing.</div><div className="assistant"><div className="avatar">✦</div><div className="answer">{blocks.map(block=>{const thread=entries.filter(e=>e.blockId===block.id),latest=thread.at(-1);return <section className="answerBlock" key={block.id}><button className="contextGear" onClick={()=>{setSelected(block.id);setDraft("")}} aria-label={`Continue conversation under ${block.title}`} title="Continue here">⚙</button><h2>{block.title}</h2>{latest?<><details className="earlierText"><summary>Earlier explanation</summary><p>{block.body}</p></details><p className="newestText">{latest.body}</p></>:<p>{block.body}</p>}{thread.length>0&&selected!==block.id&&<button className="branchLabel" onClick={()=>setSelected(block.id)}>› {thread.length} saved replies</button>}{composer(block)}</section>})}</div></div>{!selected&&<div className="bottomComposer"><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Reply to ChatGPT" rows={1}/><button disabled>↑</button></div>}</section><div className="systemLine">{selected?`Composer moved under “${selectedBlock?.title}”`:"Tap a small gear to continue directly beneath any paragraph."}</div></main>}
